name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Symlink SDK
        working-directory: ./buildscripts
        shell: bash
        run: |
          set -e
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        shell: bash
        run: |
          set -e
          ulimit -s 65535
          export LDFLAGS="-Wl,-O1,--icf=safe -Wl,-z,max-page-size=16384 -Wl,--sort-common -Wl,--as-needed -Wl,-z,pack-relative-relocs"
          export CFLAGS="-fPIC -Wno-error -Wno-error=implicit-function-declaration -O3 -mcpu=cortex-a725 -fno-plt -pipe -fvectorize -funroll-loops -flto=auto"
          export CXXFLAGS="-fPIC -Wno-error -Wno-error=implicit-function-declaration -O3 -mcpu=cortex-a725 -fno-plt -pipe -fvectorize -funroll-loops -flto=auto"
          sudo chmod +x bundle_default.sh
          sudo chmod +x build.sh
          ./bundle_default.sh
      #- name: Bundle (full)
      #  working-directory: ./buildscripts
      #  run: |
      #    sudo chmod +x bundle_full.sh
      #    ./bundle_full.sh
      - name: Bundle (encoders-gpl)
        working-directory: ./buildscripts
        shell: bash
        run: |
          set -e
          sudo chmod +x bundle_encoders-gpl.sh
          ./bundle_encoders-gpl.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./buildscripts/*.jar
            ./buildscripts/artifacts/**
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            buildscripts/*.zip
            buildscripts/artifacts/**
